export const items = {
  root: {
    index: "root",
    isFolder: false,
    children: [
      "kayinamura",
      "didas",
      "rwabununga",
      "gafurutsi",
      "frere",
      "busirinkiko",
      "mugabo",
      "alice",
      "ancila",
      "janet",
    ],
    data: "Root item",
  },
  // Abana ba Rulinda
  kayinamura: {
    index: "kayinamura",
    children: [],
    data: "Kayinamura",
    isFolder: false,
    born: "N/A",
    dead: "N/A",
  },
  didas: {
    index: "didas",
    children: [],
    data: "Didas",
    isFolder: false,
    born: "N/A",
    dead: "N/A",
  },
  rwabununga: {
    index: "rwabununga",
    isFolder: true,
    children: [
      "mukankusi",
      "kagubare",
      "kabanguka",
      "kabalungi",
      "karimukiza",
      "murebwayire",
      "kayitesi",
      "kabatesi",
    ],
    data: "Rwabununga Charles",
    born: "Jan  1928",
    dead: "Oct 2015",
  },
  gafurutsi: {
    index: "gafurutsi",
    isFolder: true,
    children: [
      "hamurungi",
      "nyagashayija",
      "edward",
      "joy",
      "theopista",
      "maridadi",
      "scola",
      "rwizima",
    ],
    data: "Gafurutsi",
    born: "N/A",
    dead: "Feb 2020",
  },
  frere: {
    index: "frere",
    isFolder: true,
    children: ["mukazi"],
    data: "Frere",
    born: "N/A",
    dead: "N/A",
  },
  busirinkiko: {
    index: "busirinkiko",
    isFolder: true,
    children: ["bashayija", "steven", "vanessa", "faith", "buconco"],
    data: "Busirinkiko",
    born: "N/A",
    dead: "N/A",
  },
  mugabo: {
    index: "mugabo",
    children: [],
    data: "Mugabo",
    isFolder: false,
    born: "N/A",
    dead: "N/A",
  },
  alice: {
    index: "alice",
    children: [],
    data: "Alice",
    isFolder: false,
    born: "N/A",
    dead: "N/A",
  },
  ancila: {
    index: "ancila",
    children: [],
    data: "Ancila",
    isFolder: false,
    born: "N/A",
    dead: "N/A",
  },
  janet: {
    index: "janet",
    children: [],
    data: "Janet",
    isFolder: false,
    born: "N/A",
    dead: " Present",
  },
  // Abana ba Rwabununga
  mukankusi: {
    index: "mukankusi",
    isFolder: true,
    children: [
      "mugoregore",
      "slyvia",
      "jenifer",
      "macondo",
      "taremwa",
      "kinyata",
      "ericka",
    ],
    data: "Mukankusi",
    born: "N/A",
    dead: "Present",
  },
  kagubare: {
    index: "kagubare",
    isFolder: true,
    children: [
      "mushabe",
      "kamukobwa",
      "kaniniri",
      "natukunda",
      "boy",
      "rwakibwana",
      "kabibi",
    ],
    data: "Kagubare Alex",
    born: "Jan 1962",
    dead: "Feb 14, 2023",
  },
  kabanguka: {
    index: "kabanguka",
    isFolder: true,
    children: [
      "kaliza",
      "rukundoKevin",
      "niyonshuti",
      "gatoElisah",
      "gakuruElia",
    ],
    data: "Kabanguka Vicent",
    born: "N/A",
    dead: "Present",
  },
  kabalungi: {
    index: "kabalungi",
    isFolder: true,
    children: ["rutare", "samKabarungi", "nkotanyi", "umuhozaAnitha"],
    data: "Kabalungi",
    born: "N/A",
    dead: "Present",
  },
  karimukiza: {
    index: "karimukiza",
    isFolder: true,
    children: ["kagubareSam", "dorcas", "phionah", "kezaIris"],
    data: "Karimukiza Samuel",
    born: "N/A",
    dead: "Present",
  },
  murebwayire: {
    index: "murebwayire",
    children: [],
    data: "Murebwayire",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  kayitesi: {
    index: "kayitesi",
    isFolder: true,
    children: ["danny", "deborah"],
    data: "Kayitesi",
    born: "N/A",
    dead: "Present",
  },
  kabatesi: {
    index: "kabatesi",
    children: [],
    data: "Kabatesi",
    isFolder: false,
    born: "N/A",
  },
  // Abana ba Frere
  mukazi: {
    index: "mukazi",
    children: [],
    data: "Mukazi",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  //   Abana ba Gafurutsi
  hamurungi: {
    index: "hamurungi",
    isFolder: true,
    children: ["mukimbiri"],
    data: "Hamurungi",
    born: "N/A",
    dead: "Present",
  },
  nyagashayija: {
    index: "nyagashayija",
    children: ["maclin", "afande", "bright", "mutoni", "shema"],
    data: "Nyagashayija",
    born: "N/A",
    dead: "Present",
  },
  edward: {
    index: "edward",
    children: ["deus", "natasha", "kevin"],
    data: "Edward",
    born: "N/A",
    dead: "Present",
  },
  joy: {
    index: "joy",
    children: [],
    data: "Joy",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  theopista: {
    index: "theopista",
    children: [],
    data: "Theopista",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  maridadi: {
    index: "maridadi",
    children: [],
    data: "Maridadi",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  scola: {
    index: "scola",
    children: [],
    data: "Scola",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  rwizima: {
    index: "rwizima",
    children: [],
    data: "Rwizima",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  // Abana ba Busirinkiko
  bashayija: {
    index: "bashayija",
    children: [],
    data: "Bashayija",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  steven: {
    index: "steven",
    children: [],
    data: "Steven",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  vanessa: {
    index: "vanessa",
    children: [],
    data: "Vanessa",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  faith: {
    index: "faith",
    children: [],
    data: "Faith",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  buconco: {
    index: "buconco",
    children: [],
    data: "Buconco",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  // Abana ba Mukankusi
  mugoregore: {
    index: "mugoregore",
    children: [],
    data: "Mugoregore",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  slyvia: {
    index: "slyvia",
    children: [],
    data: "Slyvia",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  jenifer: {
    index: "jenifer",
    children: [],
    data: "Jenifer",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  macondo: {
    index: "macondo",
    children: [],
    data: "Macondo",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  taremwa: {
    index: "taremwa",
    children: [],
    data: "Taremwa",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  kinyata: {
    index: "kinyata",
    children: [],
    data: "Mushayija Sam",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  ericka: {
    index: "ericka",
    children: [],
    data: "Ericka",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  // Abana ba Kagubare Alex
  mushabe: {
    index: "mushabe",
    children: [],
    data: "Mushabe Andrew",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  kamukobwa: {
    index: "kamukobwa",
    children: [],
    data: "Kamukobwa",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  kaniniri: {
    index: "kaniniri",
    children: [],
    data: "Moreen(Kaniniri)",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  natukunda: {
    index: "natukunda",
    children: [],
    data: "Natukunda",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  boy: {
    index: "boy",
    children: [],
    data: "Boy",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },

  rwakibwana: {
    index: "rwakibwana",
    children: [],
    data: "Rwakibwana",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  kabibi: {
    index: "kabibi",
    children: [],
    data: "Kabibi",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  // Abana ba Kabanguka
  kaliza: {
    index: "kaliza",
    children: [],
    data: "Kaliza Gloria",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  rukundoKevin: {
    index: "rukundoKevin",
    children: [],
    data: "Rukundo Kevin",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  niyonshuti: {
    index: "niyonshuti",
    children: [],
    data: "Niyonshuti Kenneth",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  gatoElisah: {
    index: "gatoElisah",
    children: [],
    data: "Gato Elisah",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  gakuruElia: {
    index: "gakuruElia",
    children: [],
    data: "Gakuru Elia",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  // Abana ba Kabalungi
  rutare: {
    index: "rutare",
    children: [],
    data: "Rutare",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  samKabarungi: {
    index: "samKabarungi",
    children: [],
    data: "Sam ",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  nkotanyi: {
    index: "nkotanyi",
    children: [],
    data: "Nkotanyi",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  umuhozaAnitha: {
    index: "umuhozaAnitha",
    children: [],
    data: "Umuhoza Anitha",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },

  // Abana ba kabao
  kagubareSam: {
    index: "kagubareSam",
    children: [],
    data: "Kagubare Samuel",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  dorcas: {
    index: "dorcas",
    children: [],
    data: "Dorcas",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  phionah: {
    index: "phionah",
    children: [],
    data: "Phionah",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  kezaIris: {
    index: "kezaIris",
    children: [],
    data: "Keza Iris",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },

  //Abana ba Kayitesi
  danny: {
    index: "danny",
    children: [],
    data: "Danny",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  deborah: {
    index: "deborah",
    children: [],
    data: "Deborah",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },
  // Abana ba Hamurungi
  mukimbiri: {
    index: "mukimbiri",
    children: [],
    data: "Mukimbiri",
    isFolder: false,
    born: "N/A",
    dead: "Present",
  },

  //Abana ba Nyagashayija
};

// Create an object with the same data as items but add photo property to each item
